services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MyVendor\Blog\:
    resource: '../Classes/*'

  MyVendor\Blog\EventListener\FileRenameListener:
    tags:
      - name: event.listener
        identifier: 'blog-file-rename-listener'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileRenamedEvent
        
  MyVendor\Blog\Command\BlogCleanupCommand:
    tags:
      - name: 'console.command'
        command: 'blog:cleanup'